# Generated by Django 3.0.5 on 2020-06-07 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20200606_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='judul')),
                ('image', models.ImageField(null=True, upload_to='article/', verbose_name='gambar')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='waktu')),
                ('countLike', models.IntegerField(null=True, verbose_name='Like')),
                ('countClap', models.IntegerField(null=True, verbose_name='Clap')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='Claps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
    ]
