# Generated by Django 3.0.5 on 2020-05-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayat',
            name='image',
            field=models.ImageField(upload_to='riwayat', verbose_name='gambar'),
        ),
    ]
