# Generated by Django 3.0.5 on 2020-05-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='judul')),
                ('description', models.TextField(verbose_name='deskripsi')),
                ('image', models.ImageField(upload_to='inspiration', verbose_name='gambar')),
                ('time', models.DateTimeField(verbose_name='waktu')),
            ],
        ),
    ]
