# Generated by Django 3.0.5 on 2020-06-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200606_0256'),
        ('inspiration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspiration',
            name='description',
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='waktu'),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='title',
            field=models.CharField(max_length=255, verbose_name='judul'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspiration', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inspiration.Inspiration')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='Clap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspiration', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inspiration.Inspiration')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
    ]
