# Generated by Django 3.0.5 on 2020-06-05 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200606_0256'),
        ('inspiration', '0002_auto_20200606_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiration',
            name='countClap',
            field=models.IntegerField(null=True, verbose_name='Clap'),
        ),
        migrations.AddField(
            model_name='inspiration',
            name='countLike',
            field=models.IntegerField(null=True, verbose_name='Like'),
        ),
        migrations.AddField(
            model_name='inspiration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
